### PR TITLE
Capstone Project

### PR DESCRIPTION
**Pull request by adarachel**
### Created a conference website using HTML, CSS & Javascript and implemented the following requirements:

- You should personalize the content of your page. Choose a topic that is different than the one in the original design.

- You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

#### Colors.
- Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
- Layout: composition and space between elements.
- The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.

#### You should build only these 2 pages:
- The home page.
- The about page.
- 
#### Each of these pages should have versions for 2 different screen sizes:

- Mobile: up to 768px wide.
- Desktop: 768px or wider.

#### Interactions:
- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.

- The mobile menu should have a close (X) button that closes the menu.

#### Dynamic page:

- The section "Featured speakers" should be created dynamically in JavaScript.
- You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

#### Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

### CODE REVIEW

**Review by uwadonat — CHANGES_REQUESTED** [review]
## Hi @adarachel ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Descriptive pull request messages ✔️
- You are following given design ✔️
- No linter errors ✔️
almoo


## Required Changes ♻️
- [ ] Please add a video containing a clear objective description of your project and a highlight about a piece of the code you find  interesting or you are proud of making.
- [ ] A link to the deployed version of your project should be in your readme file

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by adarachel** [comment]
@uwadonat Hello reviewer,
Please kindly check my readme.md file. You will find a link called 'Live Demo Link', that is the link to the live project. You will also find a link called 'Loom Video Link' that is the link to my loom video. You must not have gone through my readme file, and you just went ahead to create a nonexistent issue. Thank you.

**Comment by uwadonat** [comment]
Hi @adarachel ! Even now those two links are empty in capstone-project branch! It looks like your links are updated in main branch. Please confirm if links are updated and ask for an other review. Thank you.
Here is the output of your loom video:
Screenshot from 2022-10-26 20-30-48

**Review by ShahierNashaat — APPROVED** [review]
Hi @adarachel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
